services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/shared/src:/app/packages/shared/src

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: dev
    volumes:
      - ./apps/web/src:/app/apps/web/src
